# c00kiemon5ter (ivan.kanak@gmail.com) ~ under c00kie License
#

# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

#############################
## Put your fun stuff here ##
#############################

# view current command as title
#if [ "$SHELL" = '/bin/bash' ]; then
#	case $TERM in
#		URxvt*|rxvt*|*term)
#			set -o functrace
#			trap 'echo -ne "\e]0;$BASH_COMMAND\007"' DEBUG
#			export PS1="\e]0;$TERM\007$PS1"	;;
#	esac
#fi

# tty color theme
if [ "$TERM" = "linux" ]; then
	## set the theme name
	local THEME=console_c00kiez
	## read the theme, remove comments
	local colors=($(cat $HOME/.color_schemes/$THEME | sed 's/#.*//'))
	## apply the colors
	for index in ${!colors[@]}
	do
        printf '\e]P%x%s' $index ${colors[$index]} 
    done
	clear #for background artifacting
fi

CDPATH="${HOME}/data/:${HOME}/data/projects/git/"
PMS=clyde #pacman

source ${HOME}/.alias
source ${HOME}/.funcs

# set color variables {{{
BLACK=$(tput setaf 0)
RED=$(tput setaf 1)
GREEN=$(tput setf 2)
ORANGE=$(tput setaf 3)
BLUE=$(tput setaf 4)
PURPLE=$(tput setaf 5)
GREY=$(tput setaf 6)
WHITE=$(tput setaf 7)	
# intense
BOLD_BLACK=$(tput setaf 8)
BOLD_RED=$(tput setaf 9)
BOLD_GREEN=$(tput setaf 10)
BOLD_YELLOW=$(tput setaf 11)
BOLD_BLUE=$(tput setaf 12)
BOLD_PURPLE=$(tput setaf 13)
BOLD_GREY=$(tput setaf 14)
BOLD_WHITE=$(tput setaf 15)
# properties
NORMAL=$(tput sgr0) # reset
BOLD=$(tput bold)
UNDRLN=$(tput smul)
RMUNDRLN=$(tput rmul)
BLINK=$(tput blink)
REVERSE=$(tput rev)
# }}}
PROMPT_COMMAND=prompt
wazaaa
