# c00kiemon5ter (ivan.kanak@gmail.com) ~ under c00kie License
#

# /etc/skel/.bashrc
#
# This file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output.  So make sure this doesn't display
# anything or bad things will happen !


# Test for an interactive shell.  There is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
	# Shell is non-interactive.  Be done now!
	return
fi

#############################
## Put your fun stuff here ##
#############################

# view current command as title
#if [ "$SHELL" = '/bin/bash' ]; then
#	case $TERM in
#		URxvt*|rxvt*|*term)
#			set -o functrace
#			trap 'echo -ne "\e]0;$BASH_COMMAND\007"' DEBUG
#			export PS1="\e]0;$TERM\007$PS1"	;;
#	esac
#fi

# tty color theme
if [ "$TERM" = "linux" ]; then
	## set the theme name
	local THEME=console_c00kiez
	## read the theme, remove comments
	local colors=($(cat $HOME/.color_schemes/$THEME | sed 's/#.*//'))
	## apply the colors
	for index in ${!colors[@]}
	do
        printf '\e]P%x%s' $index ${colors[$index]} 
    done
	clear #for background artifacting
fi

export PATH=/usr/share/perl5/vendor_perl/auto/share/dist/Cope:/bin:/usr/bin:/sbin:/usr/sbin:/usr/bin/perlbin/site:/usr/bin/perlbin/vendor:/usr/lib/perl5/core_perl/bin:/home/c00kiemon5ter/.bin:/usr/local/bin

export CDPATH="${HOME}/data/:${HOME}/data/projects/git/"
export PMS=clyde #pacman

export MPD_HOST=127.0.0.1
export MPD_PORT=6600

source ${HOME}/.alias
source ${HOME}/.funcs

# set color variables {{{
export DARK=$(tput setaf 0)
export RED=$(tput setaf 1)
export GREEN=$(tput setf 2)
export ORANGE=$(tput setaf 3)
export LIGHTBLUE=$(tput setaf 4)
export MAUV=$(tput setaf 5)
export DARKGREY=$(tput setaf 6)
export WHITE=$(tput setaf 7)	

export BOLDDARK=$(tput setaf 8)
export BOLDRED=$(tput setaf 9)
export BOLDGREEN=$(tput setaf 10)
export GOLD=$(tput setaf 11)
export BLUE=$(tput setaf 12)
export PURPLE=$(tput setaf 13)
export GREY=$(tput setaf 14)
export BOLDWHITE=$(tput setaf 15)

export BLACK=$(tput setaf 16)
export NORMAL=$(tput sgr0) # reset
export DIM=$(tput dim)
export BOLD=$(tput bold)
export UNDRLN=$(tput smul)
export RMUNDRLN=$(tput rmul)
export BLINK=$(tput blink)
export REVERSE=$(tput rev)
export INVISIBLE=$(tput invis)
# }}}

export PROMPT_COMMAND=prompt
wazaaa
