#!/bin/bash

## merge xdefault settings to X db
#xrdb -merge $HOME/.Xdefaults &

## urxvt daemon
urxvtd -q -o -f

## toogle keyboard layout with S-A
setxkbmap -model evdev -layout us,gr -variant extended -option grp_led:scroll,eurosign:e,grp:alt_shift_toggle &

## set the wallpaper
sh ${HOME}/.fehbg &

## hide mouse after some idle time
unclutter &

## start the X session
exec openbox-session

